# Generated by Django 5.0.1 on 2024-03-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_task_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonTask',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=None, null=True),
        ),
    ]
