# Generated by Django 5.0.1 on 2024-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_super_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_task',
            name='task_heading',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_heading',
            field=models.CharField(max_length=20),
        ),
    ]
