# Generated by Django 5.0.1 on 2024-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_super_task_task_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='designation',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='specialization',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='year_of_exp',
            field=models.IntegerField(default=0),
        ),
    ]
