# Generated by Django 5.0.1 on 2024-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_supervisor_department_supervisor_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='designation',
            field=models.CharField(default='Assistant professor', max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='specialization',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
