# Generated by Django 5.0.1 on 2024-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_supervisor_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='designation',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='specialization',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
