# Generated by Django 5.0.1 on 2024-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_supervisor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_task',
            name='note',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='designation',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
