# Generated by Django 5.0.3 on 2024-03-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pre_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='type_of_project',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
