# Generated by Django 5.0.3 on 2024-03-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_project_department_project_type_of_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
